# -*- coding: utf8 -*-

from vectors import Vect2D
# COLORS

COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_RED = (255, 0, 0)
COLOR_GRAY1 = (200, 200, 200)
COLOR_RAND1 = (0, 200, 200)

# ELEMENT CONFIG

NEW_ELEMENT_X = 3
NEW_ELEMENT_Y = 0

ELEMENT_FILL = 'E'
ELEMENT_BLANK = ' '

BLOCK_SIZE = 20  # pixels


# SCREEN CONFIG

SCREEN_WIDTH = 800  # pixels
SCREEN_HEIGHT = 600  # pixels

BOARD_OFFSET = Vect2D(50, 50)

NXT_E_BOX_OFFSET = Vect2D(300, 50)
NXT_E_BOX_SIZE = Vect2D(100, 100)
NXT_E_BLOCK_SIZE = Vect2D(20, 20)


# BOARD CONFIG

WALL_LEFT = 'L'
WALL_RIGHT = 'R'
FLOOR = 'F'
BACKGROUND_FILL = '_'
BACKGROUND_COLOR = COLOR_BLACK

BOARD_HEIGHT = 20
BOARD_WIDTH = 10


# GAME

MOVE_LEFT = 1
MOVE_UP = 2
MOVE_RIGHT = 3
MOVE_DOWN = 4
MOVE_ESCAPE = 5
MOVE_SMASH = 6

STEP_SECONDS = 0.1

STATE_NEW_GAME = 1
STATE_PLAYING = 2
STATE_PAUSED = 3
STATE_GAME_OVER = 4
